sudo: required
services:
  - docker

before_install:
  - docker build -t jayce/react-test -f ./client/Dockerfile.dev  ./client
  
script:
  - docker run jayce/react-test npm test -- --coverage
 
after_success:
  - docker build -t jayceayres/multi-client ./client  
  - docker build -t jayceayres/multi-nginx ./nginx  
  - docker build -t jayceayres/multi-server ./server  
  - docker build -t jayceayres/multi-worker ./worker  
  #
  - echo "$DOCKER_PSW" | docker login -u "$DOCKER_ID" --password-stdin
  
  - docker push jayceayres/multi-client
  - docker push jayceayres/multi-nginx 
  - docker push jayceayres/multi-server 
  - docker push jayceayres/multi-worker 